# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'

reports:
  exclude_contracts:
    - SafeMath
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  from_key2: ${PRIVATE_KEY2}
  from_key3: ${PRIVATE_KEY3}
networks:
  kovan:
    verify: True
  rinkeby:
    verify: True
  development:
    verify: False
